INHERIT: !ENV MKDOCS_NUMTIDE_THEME

### Site metadata ###

## - This will be the name displayed in docs header
site_name: Numtide custom docs
## - change this according to the relevant Numtide repo description
site_description: Custom MkDocs base Repo
## - change this according to the relevant Numtide repo docs location - eg https://numtide.github.io/treefmt/
site_url: https://numtide.github.io/mkdocs-numtide 
## - change this according to the relevant Numtide repo url
repo_url: https://github.com/numtide/mkdocs-numtide 
repo_name: 'numtide/mkdocs-numtide'
edit_uri: edit/main/docs
